[theme]
base = "light"
primaryColor = "#6A5ACD"  # slateBlue
backgroundColor = "#F5FFFA"  # mintCream
secondaryBackgroundColor = "#8FBC8F"  # darkSeaGreen
borderRadius = "0.5rem"

[theme.sidebar]
backgroundColor = "#F0F8FF"  # aliceBlue
secondaryBackgroundColor = "#87CEEB"  # skyBlue